### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by saucompeng** [bubuntux/docker-riot-web#4]
Hi, How can activate https connection? VoIP can't use via http.

**Comment by bubuntux** [comment]
this image is based on nginx, so configure https as you would using nginx

http://nginx.org/en/docs/http/configuring_https_servers.html
https://medium.com/faun/setting-up-ssl-certificates-for-nginx-in-docker-environ-e7eec5ebb418

feel free to submit a pull request with documentation update on the README.md to enable this, ty
