### ISSUE TITLE
v1.7.15 renames the built artifacts from riot-vX.Y.Z.tar.gz to element-vX.Y.Z.tar.gz

### ISSUE THREAD

**Issue by anshockm** [bubuntux/docker-riot-web#5]
[https://github.com/vector-im/element-web/releases](https://github.com/vector-im/element-web/releases):

v1.7.15

@RiotRobot RiotRobot released this 9 days ago · 22 commits to develop since this release
Packaging change

This release renames the built artifacts from riot-vX.Y.Z.tar.gz to element-vX.Y.Z.tar.gz. If you are using a script to package or deploy Element, you may need to adjust that for the new name.
...

**Comment by bubuntux** [comment]
gotcha, let me try to fix it
Thanks for the headsup @anshockm

**Comment by bubuntux** [comment]
build has being fixed, still need to clean up a few things on the readme
